# Generated by Django 3.0.3 on 2020-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='comment',
            field=models.TextField(),
        ),
    ]
