# Generated by Django 3.0.3 on 2020-05-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200522_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimages',
            old_name='blog',
            new_name='blog_super',
        ),
    ]
