# Generated by Django 3.0.3 on 2020-05-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200522_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimages',
            name='blog_super',
        ),
    ]
